package com.apitest.exception;

public enum ApiErrorCode {
	ACCESS_DENIED, MISSING_QUERY_PARAM, INCORRECT_CREDENTIALS, INVALID_INPUT, RESOURCE_NOT_FOUND, EMP_EMAIL_NOT_VERIFIED, RESOURCE_INACTIVE,
	NO_ACTIVE_SUBSCRIPTION, EMPNO_ALREADY_EXIST, TRIAL_EXPIRED, INVALID_PASSWORD,INTERNAL_ERROR
}
